name: KNEE.LONDON
favicon: null
layout_spectrum: 0.12813
typography_spectrum: 0.87572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.752475212328136
  lightness: 0.16592087945900857
  saturation: 0.8615659861825407
  rhythmicContrast: 0.27744461758993566
purpose: []
